name: Build and push image to Harbor

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v3
      with:
        registry: eccr.ecmwf.int
        username: ${{ secrets.HARBOR_USERNAME  }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - uses: actions/checkout@v4
    # - name: Create Docker context
    #   run: docker buildx create --name app-ctx --platform="linux/amd64"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
    - name: Build the Docker image
      uses: docker/build-push-action@v5
      with: 
        context: .
        platforms: linux/amd64
        push: true
        tags: eccr.ecmwf.int/c3s-applications/climate-pulse:latest
      
      
      
      